export const aiDirectoryReviewedAt = "2026-07-14"

export const aiDirectoryCategories = [
  {
    id: "assistants",
    title: "AI Assistants & Search",
    titleZh: "AI 助手与搜索",
    description: "General-purpose assistants, answer engines, and multimodal search.",
    descriptionZh: "通用助手、答案引擎与多模态搜索。",
  },
  {
    id: "research",
    title: "Research & Learning",
    titleZh: "研究与学习",
    description: "Source-grounded research, literature discovery, and study support.",
    descriptionZh: "基于来源资料的研究、文献发现与学习辅助。",
  },
  {
    id: "productivity",
    title: "Writing & Productivity",
    titleZh: "写作与效率",
    description: "Writing, translation, presentations, and everyday knowledge work.",
    descriptionZh: "写作、翻译、演示文稿与日常知识工作。",
  },
  {
    id: "coding",
    title: "Coding & App Building",
    titleZh: "编程与应用构建",
    description: "Code assistants, autonomous engineering, and prompt-to-app builders.",
    descriptionZh: "代码助手、自主软件工程与自然语言应用构建。",
  },
  {
    id: "image",
    title: "Image & Design",
    titleZh: "图像与设计",
    description: "Image generation, editing, brand assets, and production design.",
    descriptionZh: "图像生成、编辑、品牌素材与设计制作。",
  },
  {
    id: "video",
    title: "Video & Avatars",
    titleZh: "视频与数字人",
    description: "Text-to-video, editing, avatars, dubbing, and short-form production.",
    descriptionZh: "文生视频、剪辑、数字人、配音与短视频制作。",
  },
  {
    id: "audio",
    title: "Audio, Voice & Music",
    titleZh: "音频、语音与音乐",
    description: "Voice generation, music creation, transcription, and audio cleanup.",
    descriptionZh: "语音生成、音乐创作、转录与音频清理。",
  },
  {
    id: "automation",
    title: "Automation & Agents",
    titleZh: "自动化与智能体",
    description: "Workflow automation and agents that complete multi-step tasks.",
    descriptionZh: "工作流自动化与可执行多步骤任务的智能体。",
  },
] as const

export type AiDirectoryCategoryId = (typeof aiDirectoryCategories)[number]["id"]

export type AiDirectoryTool = {
  slug: string
  name: string
  url: string
  category: AiDirectoryCategoryId
  description: string
  descriptionZh: string
  tags: string[]
  popular?: boolean
  trending?: boolean
  featured?: boolean
}

export const aiDirectoryTools: AiDirectoryTool[] = [
  {
    slug: "chatgpt",
    name: "ChatGPT",
    url: "https://chatgpt.com/",
    category: "assistants",
    description: "OpenAI's general-purpose assistant for writing, analysis, coding, images, and connected workflows.",
    descriptionZh: "OpenAI 通用助手，覆盖写作、分析、编程、图像与可连接外部工具的工作流。",
    tags: ["multimodal", "writing", "coding"],
    popular: true,
    featured: true,
  },
  {
    slug: "gemini",
    name: "Gemini",
    url: "https://gemini.google.com/",
    category: "assistants",
    description: "Google's multimodal assistant with deep integration across Search, Workspace, images, and video.",
    descriptionZh: "Google 多模态助手，深度连接搜索、Workspace、图像与视频能力。",
    tags: ["multimodal", "google", "workspace"],
    popular: true,
    trending: true,
    featured: true,
  },
  {
    slug: "claude",
    name: "Claude",
    url: "https://claude.ai/",
    category: "assistants",
    description: "Anthropic's assistant for reasoning, working with long documents, coding, and connected workflows.",
    descriptionZh: "Anthropic 助手，可用于推理、长文档处理、编程与可连接外部工具的工作流。",
    tags: ["reasoning", "documents", "coding"],
    popular: true,
    trending: true,
    featured: true,
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    url: "https://www.perplexity.ai/",
    category: "assistants",
    description: "An answer engine that searches the web and presents concise responses with source links.",
    descriptionZh: "联网答案引擎，以简洁回答和来源链接组织搜索结果。",
    tags: ["search", "citations", "research"],
    popular: true,
    featured: true,
  },
  {
    slug: "microsoft-copilot",
    name: "Microsoft Copilot",
    url: "https://copilot.microsoft.com/",
    category: "assistants",
    description: "Microsoft's consumer assistant for web answers, content creation, and everyday productivity.",
    descriptionZh: "Microsoft 面向消费者的助手，适合联网问答、内容创作与日常效率任务。",
    tags: ["search", "microsoft", "productivity"],
    popular: true,
  },
  {
    slug: "grok",
    name: "Grok",
    url: "https://grok.com/",
    category: "assistants",
    description: "xAI's real-time assistant for web and social context, reasoning, coding, and media generation.",
    descriptionZh: "xAI 的实时助手，覆盖网络与社交语境、推理、编程和图像与视频生成。",
    tags: ["real-time", "reasoning", "social"],
    popular: true,
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    url: "https://chat.deepseek.com/",
    category: "assistants",
    description: "DeepSeek's assistant for reasoning and coding, backed by the company's open model releases and research.",
    descriptionZh: "DeepSeek 的推理与编程助手，关联其开放模型发布与研究工作。",
    tags: ["reasoning", "coding", "open models"],
    popular: true,
  },
  {
    slug: "poe",
    name: "Poe",
    url: "https://poe.com/",
    category: "assistants",
    description: "Quora's multi-model hub for comparing assistants and using community-created bots.",
    descriptionZh: "Quora 的多模型平台，可比较不同助手并使用社区机器人。",
    tags: ["multi-model", "bots", "community"],
    popular: true,
  },

  {
    slug: "notebooklm",
    name: "NotebookLM",
    url: "https://notebooklm.google.com/",
    category: "research",
    description: "A source-grounded Google notebook that explains uploaded material and creates audio overviews.",
    descriptionZh: "基于导入来源资料的 Google 研究笔记，可解释内容并生成音频概览。",
    tags: ["sources", "notes", "audio overview"],
    popular: true,
    featured: true,
  },
  {
    slug: "elicit",
    name: "Elicit",
    url: "https://elicit.com/",
    category: "research",
    description: "A research assistant for finding papers, extracting evidence, and building literature reviews.",
    descriptionZh: "用于发现论文、提取证据并构建文献综述的研究助手。",
    tags: ["papers", "evidence", "literature review"],
  },
  {
    slug: "consensus",
    name: "Consensus",
    url: "https://consensus.app/",
    category: "research",
    description: "An academic search engine that summarizes findings from peer-reviewed research.",
    descriptionZh: "面向同行评审研究的学术搜索引擎，可汇总研究结论。",
    tags: ["academic", "search", "citations"],
    popular: true,
  },
  {
    slug: "scite",
    name: "Scite",
    url: "https://scite.ai/",
    category: "research",
    description: "Smart citation analysis showing whether later papers support, mention, or contrast a claim.",
    descriptionZh: "智能引文分析，显示后续论文对某项主张的支持、提及或反驳关系。",
    tags: ["citations", "evidence", "papers"],
  },
  {
    slug: "scispace",
    name: "SciSpace",
    url: "https://scispace.com/",
    category: "research",
    description: "A literature workspace for discovering, reading, explaining, and comparing scientific papers.",
    descriptionZh: "用于发现、阅读、解释和比较科学论文的文献工作区。",
    tags: ["papers", "pdf", "literature"],
  },
  {
    slug: "semantic-scholar",
    name: "Semantic Scholar",
    url: "https://www.semanticscholar.org/",
    category: "research",
    description: "A free AI-powered scholarly search service with paper, author, and citation discovery.",
    descriptionZh: "免费的 AI 学术搜索服务，支持论文、作者与引文发现。",
    tags: ["academic", "search", "free"],
  },
  {
    slug: "research-rabbit",
    name: "ResearchRabbit",
    url: "https://www.researchrabbit.ai/",
    category: "research",
    description: "A visual discovery tool for exploring connected papers, authors, and research collections.",
    descriptionZh: "可视化研究发现工具，用于探索相关论文、作者与研究集合。",
    tags: ["discovery", "citations", "visual map"],
  },
  {
    slug: "wayground",
    name: "Wayground",
    url: "https://wayground.com/",
    category: "research",
    description: "The learning platform formerly known as Quizizz, with AI-assisted lessons and assessments.",
    descriptionZh: "原 Quizizz 学习平台，提供 AI 辅助课程、练习与评估。",
    tags: ["education", "quiz", "teachers"],
    popular: true,
  },

  {
    slug: "grammarly",
    name: "Grammarly",
    url: "https://www.grammarly.com/",
    category: "productivity",
    description: "A writing assistant for grammar, tone, rewriting, and workplace communication.",
    descriptionZh: "用于语法、语气、改写与职场沟通的写作助手。",
    tags: ["writing", "editing", "tone"],
    popular: true,
  },
  {
    slug: "notion-ai",
    name: "Notion AI",
    url: "https://www.notion.com/product/ai",
    category: "productivity",
    description: "AI search, writing, meeting notes, and connected knowledge inside the Notion workspace.",
    descriptionZh: "集成在 Notion 工作区中的 AI 搜索、写作、会议记录与知识连接。",
    tags: ["workspace", "notes", "knowledge"],
    popular: true,
  },
  {
    slug: "deepl",
    name: "DeepL",
    url: "https://www.deepl.com/",
    category: "productivity",
    description: "A translation and writing platform for multilingual communication.",
    descriptionZh: "用于多语言沟通的翻译与写作平台。",
    tags: ["translation", "writing", "languages"],
    popular: true,
  },
  {
    slug: "quillbot",
    name: "QuillBot",
    url: "https://quillbot.com/",
    category: "productivity",
    description: "A writing suite for paraphrasing, grammar checking, summarizing, and citation support.",
    descriptionZh: "提供改写、语法检查、摘要与引用辅助的写作套件。",
    tags: ["paraphrase", "grammar", "summary"],
    popular: true,
  },
  {
    slug: "gamma",
    name: "Gamma",
    url: "https://gamma.app/",
    category: "productivity",
    description: "A presentation, document, and website builder that generates editable visual content from prompts.",
    descriptionZh: "可从提示词生成并编辑演示文稿、文档和网页视觉内容的工具。",
    tags: ["presentations", "documents", "design"],
    popular: true,
    featured: true,
  },
  {
    slug: "jasper",
    name: "Jasper",
    url: "https://www.jasper.ai/",
    category: "productivity",
    description: "A brand-focused content platform for marketing teams, campaigns, and repeatable workflows.",
    descriptionZh: "面向营销团队的品牌内容平台，适用于活动与可复用工作流。",
    tags: ["marketing", "brand", "content"],
    popular: true,
  },
  {
    slug: "copy-ai",
    name: "Copy.ai",
    url: "https://www.copy.ai/",
    category: "productivity",
    description: "A go-to-market platform for automating sales and marketing content workflows.",
    descriptionZh: "用于自动化销售与营销内容工作流的增长平台。",
    tags: ["sales", "marketing", "automation"],
    popular: true,
  },
  {
    slug: "beautiful-ai",
    name: "Beautiful.ai",
    url: "https://www.beautiful.ai/",
    category: "productivity",
    description: "Presentation software with AI-assisted layouts and structured business storytelling.",
    descriptionZh: "提供 AI 辅助排版与结构化商业叙事的演示文稿工具。",
    tags: ["presentations", "slides", "business"],
    popular: true,
  },

  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    url: "https://github.com/features/copilot",
    category: "coding",
    description: "GitHub's coding assistant for completion, chat, code review, and agent-driven development.",
    descriptionZh: "GitHub 代码助手，覆盖补全、对话、代码审查与智能体开发。",
    tags: ["code", "github", "agents"],
    popular: true,
  },
  {
    slug: "cursor",
    name: "Cursor",
    url: "https://cursor.com/",
    category: "coding",
    description: "An AI-first code editor for repository-aware chat, edits, and autonomous engineering tasks.",
    descriptionZh: "AI 原生代码编辑器，支持仓库级对话、编辑与自主工程任务。",
    tags: ["editor", "code", "agents"],
    popular: true,
    featured: true,
  },
  {
    slug: "replit",
    name: "Replit",
    url: "https://replit.com/",
    category: "coding",
    description: "A browser development platform with agents that build, run, and deploy full applications.",
    descriptionZh: "浏览器开发平台，可用智能体构建、运行并部署完整应用。",
    tags: ["app builder", "deploy", "agents"],
    popular: true,
    trending: true,
  },
  {
    slug: "lovable",
    name: "Lovable",
    url: "https://lovable.dev/",
    category: "coding",
    description: "A prompt-to-app builder for generating and iterating full-stack web applications.",
    descriptionZh: "用于生成和迭代全栈 Web 应用的自然语言构建器。",
    tags: ["app builder", "full-stack", "no-code"],
    popular: true,
    trending: true,
  },
  {
    slug: "bolt-new",
    name: "Bolt.new",
    url: "https://bolt.new/",
    category: "coding",
    description: "StackBlitz's browser-based agent for creating, running, and editing web applications.",
    descriptionZh: "StackBlitz 的浏览器应用智能体，可创建、运行和编辑 Web 应用。",
    tags: ["app builder", "browser", "full-stack"],
    popular: true,
  },
  {
    slug: "v0",
    name: "v0",
    url: "https://v0.dev/",
    category: "coding",
    description: "Vercel's AI product builder for generating interfaces and shipping web applications.",
    descriptionZh: "Vercel 的 AI 产品构建器，用于生成界面并交付 Web 应用。",
    tags: ["ui", "app builder", "vercel"],
    popular: true,
  },
  {
    slug: "tabnine",
    name: "Tabnine",
    url: "https://www.tabnine.com/",
    category: "coding",
    description: "An enterprise coding platform for completions, chat, agentic workflows, and private deployment.",
    descriptionZh: "企业级编程平台，提供代码补全、对话、智能体工作流与私有部署。",
    tags: ["enterprise", "code", "private deployment"],
    popular: true,
  },
  {
    slug: "devin",
    name: "Devin",
    url: "https://devin.ai/",
    category: "coding",
    description: "Cognition's autonomous software engineering agent for delegated development tasks.",
    descriptionZh: "Cognition 的自主软件工程智能体，可接管明确的开发任务。",
    tags: ["engineering", "agents", "automation"],
  },

  {
    slug: "canva-magic-studio",
    name: "Canva Magic Studio",
    url: "https://www.canva.com/magic/",
    category: "image",
    description: "Canva's integrated AI suite for graphics, presentations, images, video, and branded content.",
    descriptionZh: "Canva 一体化 AI 套件，覆盖图形、演示、图像、视频与品牌内容。",
    tags: ["design", "templates", "brand"],
    popular: true,
    featured: true,
  },
  {
    slug: "midjourney",
    name: "Midjourney",
    url: "https://www.midjourney.com/",
    category: "image",
    description: "An image generation platform for creating and editing visual concepts from prompts and references.",
    descriptionZh: "用于根据提示词和参考图创建、编辑视觉概念的图像生成平台。",
    tags: ["image generation", "art", "creative"],
    popular: true,
  },
  {
    slug: "adobe-firefly",
    name: "Adobe Firefly",
    url: "https://firefly.adobe.com/",
    category: "image",
    description: "Adobe's generative workspace for images, vectors, video, and Creative Cloud workflows.",
    descriptionZh: "Adobe 生成式创作空间，覆盖图像、矢量、视频与 Creative Cloud 工作流。",
    tags: ["adobe", "image generation", "commercial"],
    popular: true,
  },
  {
    slug: "ideogram",
    name: "Ideogram",
    url: "https://ideogram.ai/",
    category: "image",
    description: "An image generator with tools for typography, graphic design, posters, and brand concepts.",
    descriptionZh: "提供文字呈现、平面设计、海报与品牌概念能力的图像生成器。",
    tags: ["typography", "image generation", "posters"],
    popular: true,
  },
  {
    slug: "leonardo-ai",
    name: "Leonardo.Ai",
    url: "https://leonardo.ai/",
    category: "image",
    description: "An image platform for asset generation, editing, style control, and team workflows.",
    descriptionZh: "支持素材生成、编辑、风格控制与团队工作流的图像平台。",
    tags: ["assets", "image generation", "editing"],
    popular: true,
  },
  {
    slug: "freepik-ai",
    name: "Freepik AI Suite",
    url: "https://www.freepik.com/ai",
    category: "image",
    description: "A broad creative suite combining generation, editing, stock assets, mockups, and video tools.",
    descriptionZh: "综合创意套件，结合生成、编辑、图库素材、样机与视频工具。",
    tags: ["stock", "design", "image generation"],
    popular: true,
  },
  {
    slug: "photoroom",
    name: "Photoroom",
    url: "https://www.photoroom.com/",
    category: "image",
    description: "An AI photo studio for product imagery, background work, resizing, and commerce assets.",
    descriptionZh: "面向商品图、背景处理、尺寸调整与电商素材的 AI 图片工作室。",
    tags: ["product photos", "background", "commerce"],
    popular: true,
  },
  {
    slug: "remove-bg",
    name: "remove.bg",
    url: "https://www.remove.bg/",
    category: "image",
    description: "A focused service for automatic image background removal and replacement.",
    descriptionZh: "用于自动移除和替换图片背景的专用服务。",
    tags: ["background", "photo", "editing"],
    popular: true,
  },

  {
    slug: "runway",
    name: "Runway",
    url: "https://runwayml.com/",
    category: "video",
    description: "A generative video platform for creating, transforming, and editing footage.",
    descriptionZh: "用于创建、变换与编辑视频素材的生成式视频平台。",
    tags: ["video generation", "editing", "creative"],
    popular: true,
    featured: true,
  },
  {
    slug: "luma-dream-machine",
    name: "Luma Dream Machine",
    url: "https://lumalabs.ai/dream-machine",
    category: "video",
    description: "Luma's workspace for text-to-video, image-to-video, and prompt-based video modification.",
    descriptionZh: "Luma 的视频创作工作区，支持文生视频、图生视频与基于提示词的视频修改。",
    tags: ["video generation", "image to video", "video editing"],
  },
  {
    slug: "kling-ai",
    name: "Kling AI",
    url: "https://klingai.com/",
    category: "video",
    description: "An image and video generation platform with motion and camera-control options.",
    descriptionZh: "提供运动与镜头控制选项的图像和视频生成平台。",
    tags: ["video generation", "motion", "image to video"],
    trending: true,
    popular: true,
  },
  {
    slug: "hailuo-ai",
    name: "Hailuo AI",
    url: "https://hailuoai.video/",
    category: "video",
    description: "A text-to-video and image-to-video platform for short-form clips.",
    descriptionZh: "用于制作短片的文生视频与图生视频平台。",
    tags: ["video generation", "cinematic", "image to video"],
    trending: true,
  },
  {
    slug: "pixverse",
    name: "PixVerse",
    url: "https://pixverse.ai/",
    category: "video",
    description: "A video generator with effects, templates, character clips, and iteration tools.",
    descriptionZh: "提供特效、模板、角色短片与迭代工具的视频生成器。",
    tags: ["video generation", "effects", "templates"],
    trending: true,
  },
  {
    slug: "capcut",
    name: "CapCut",
    url: "https://www.capcut.com/",
    category: "video",
    description: "A video editor with AI captions, effects, background tools, avatars, and text-to-video features.",
    descriptionZh: "集成 AI 字幕、特效、背景、数字人与文生视频功能的视频编辑器。",
    tags: ["editing", "captions", "short video"],
    popular: true,
  },
  {
    slug: "heygen",
    name: "HeyGen",
    url: "https://www.heygen.com/",
    category: "video",
    description: "An AI avatar and translation platform for business videos, localization, and presentations.",
    descriptionZh: "面向商业视频、本地化与演示的 AI 数字人和翻译平台。",
    tags: ["avatars", "translation", "business video"],
    popular: true,
  },
  {
    slug: "synthesia",
    name: "Synthesia",
    url: "https://www.synthesia.io/",
    category: "video",
    description: "An enterprise avatar video platform for training, enablement, and multilingual communication.",
    descriptionZh: "企业级数字人视频平台，适合培训、赋能与多语言沟通。",
    tags: ["avatars", "enterprise", "training"],
    popular: true,
  },

  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    url: "https://elevenlabs.io/",
    category: "audio",
    description: "A voice platform for text-to-speech, dubbing, voice design, and audio production.",
    descriptionZh: "用于文本转语音、配音、声音设计与音频制作的语音平台。",
    tags: ["voice", "dubbing", "text to speech"],
    popular: true,
    trending: true,
    featured: true,
  },
  {
    slug: "suno",
    name: "Suno",
    url: "https://suno.com/",
    category: "audio",
    description: "A music generation platform for creating songs from text prompts.",
    descriptionZh: "可根据文本提示词创作歌曲的音乐生成平台。",
    tags: ["music", "songs", "audio generation"],
    popular: true,
  },
  {
    slug: "udio",
    name: "Udio",
    url: "https://www.udio.com/",
    category: "audio",
    description: "A music creation tool for generating, extending, remixing, and refining tracks.",
    descriptionZh: "音乐创作工具，支持生成、延展、重混与细化曲目。",
    tags: ["music", "remix", "audio generation"],
    popular: true,
  },
  {
    slug: "adobe-podcast",
    name: "Adobe Podcast",
    url: "https://podcast.adobe.com/",
    category: "audio",
    description: "Browser-based speech enhancement, recording, and podcast cleanup from Adobe.",
    descriptionZh: "Adobe 的浏览器语音增强、录音与播客清理工具。",
    tags: ["podcast", "enhance speech", "recording"],
    popular: true,
  },
  {
    slug: "descript",
    name: "Descript",
    url: "https://www.descript.com/",
    category: "audio",
    description: "A text-based editor for podcasts and video with transcription, voice, and cleanup tools.",
    descriptionZh: "文本式播客与视频编辑器，包含转录、语音与清理工具。",
    tags: ["podcast", "transcription", "editing"],
    popular: true,
  },
  {
    slug: "otter-ai",
    name: "Otter.ai",
    url: "https://otter.ai/",
    category: "audio",
    description: "Meeting transcription and notes with searchable summaries, action items, and team sharing.",
    descriptionZh: "会议转录与记录工具，提供可搜索摘要、行动项与团队分享。",
    tags: ["meetings", "transcription", "notes"],
    popular: true,
  },
  {
    slug: "krisp",
    name: "Krisp",
    url: "https://krisp.ai/",
    category: "audio",
    description: "AI meeting audio with noise cancellation, transcription, summaries, and accent conversion.",
    descriptionZh: "AI 会议音频工具，支持降噪、转录、摘要与口音转换。",
    tags: ["noise cancellation", "meetings", "transcription"],
    popular: true,
  },
  {
    slug: "murf-ai",
    name: "Murf AI",
    url: "https://murf.ai/",
    category: "audio",
    description: "A business voiceover studio for narration, localization, and production-ready speech.",
    descriptionZh: "商业配音工作室，用于旁白、本地化与生产级语音制作。",
    tags: ["voiceover", "text to speech", "business"],
    popular: true,
  },

  {
    slug: "n8n",
    name: "n8n",
    url: "https://n8n.io/",
    category: "automation",
    description: "A workflow automation platform with AI agents, integrations, and self-hosting options.",
    descriptionZh: "提供 AI 智能体、集成与自托管选项的工作流自动化平台。",
    tags: ["workflows", "agents", "self-hosted"],
    popular: true,
    featured: true,
  },
  {
    slug: "zapier-ai",
    name: "Zapier AI",
    url: "https://zapier.com/ai",
    category: "automation",
    description: "AI automation across a large app ecosystem, including agents, actions, and workflow building.",
    descriptionZh: "连接大型应用生态的 AI 自动化平台，包含智能体、动作与工作流构建。",
    tags: ["workflows", "integrations", "agents"],
    popular: true,
  },
  {
    slug: "make",
    name: "Make",
    url: "https://www.make.com/",
    category: "automation",
    description: "A visual automation platform for connecting apps, data, APIs, and AI-driven workflows.",
    descriptionZh: "可视化自动化平台，用于连接应用、数据、API 与 AI 工作流。",
    tags: ["workflows", "integrations", "visual builder"],
    popular: true,
  },
  {
    slug: "manus",
    name: "Manus",
    url: "https://manus.im/",
    category: "automation",
    description: "A general agent that carries out open-ended research, analysis, content, and operational tasks.",
    descriptionZh: "可执行开放式研究、分析、内容与运营任务的通用智能体。",
    tags: ["general agent", "research", "operations"],
    popular: true,
    trending: true,
  },
  {
    slug: "genspark",
    name: "Genspark",
    url: "https://www.genspark.ai/",
    category: "automation",
    description: "An agent workspace for research, documents, slides, calls, and multi-step tasks.",
    descriptionZh: "覆盖研究、文档、幻灯片、通话与多步骤任务的智能体工作区。",
    tags: ["general agent", "research", "documents"],
    trending: true,
  },
  {
    slug: "gumloop",
    name: "Gumloop",
    url: "https://www.gumloop.com/",
    category: "automation",
    description: "A visual AI automation builder for web research, enrichment, content, and business processes.",
    descriptionZh: "可视化 AI 自动化构建器，适合网络研究、数据丰富、内容与业务流程。",
    tags: ["workflows", "web research", "no-code"],
    trending: true,
  },
  {
    slug: "lindy",
    name: "Lindy",
    url: "https://www.lindy.ai/",
    category: "automation",
    description: "A no-code agent platform for email, meetings, support, sales, and back-office workflows.",
    descriptionZh: "无代码智能体平台，覆盖邮件、会议、客服、销售与后台流程。",
    tags: ["agents", "no-code", "business"],
    trending: true,
  },
  {
    slug: "relevance-ai",
    name: "Relevance AI",
    url: "https://relevanceai.com/",
    category: "automation",
    description: "A platform for building and operating AI agent teams with tools, knowledge, and workflows.",
    descriptionZh: "用于构建和运行 AI 智能体团队的平台，支持工具、知识与工作流。",
    tags: ["agent teams", "workflows", "business"],
    trending: true,
  },
]

export function getAiDirectoryCategory(id: AiDirectoryCategoryId) {
  return aiDirectoryCategories.find((category) => category.id === id)!
}
